name = "The Identity Platform for Developers"
email = "developers@okta.com"
baseURL = "https://developer.okta.com"
languageCode = "en-us"
title = "Okta Developer"
theme = "okta"
#pygmentsStyle = "manni"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

disqusshortname = "oktadevblog"
paginate = 10
paginatePath = "page"

[permalinks]
  blog = "/blog/:year/:month/:day/:filename/"

[params]
  twitter_username = "OktaDev"
  github_username = "oktadeveloper"
  github_base_url = "https://github.com/okta/okta.github.io/tree/source/hugo/content/"
  github_edit_url = "https://github.com/okta/okta.github.io/edit/source/hugo/content/"
  dev_forum = "https://devforum.okta.com/"
  description = "Secure, scalable, and highly available authentication and user management for any app."
  documentation_dirs = [ "code", "documentation", "docs", "standards", "use_cases", "reference" ]
  auth_references = [ "/docs/api/resources/authn", "/docs/api/resources/oauth2", "/docs/api/resources/oidc", "/docs/api/resources/social_authentication", "/docs/api/resources/sessions"]
  api_references = [ "/docs/api/resources/authorization-servers", "/docs/api/resources/apps", "/docs/api/resources/events", "/docs/api/resources/oauth-clients", "/docs/api/resources/factor_admin","/docs/api/resources/factors", "/docs/api/resources/groups","/docs/api/resources/idps","/docs/api/resources/policy","/docs/api/resources/roles","/docs/api/resources/schemas","/docs/api/resources/system_log","/docs/api/resources/templates","/docs/api/resources/tokens","/docs/api/resources/trusted-origins","/docs/api/resources/users","/docs/api/resources/zones"]
  reference = [ "/reference/api_reference/", "/reference/getting_started/", "/reference/authentication_reference/"]
  how_to = [ "/how-to/byo_saml/", "/how-to/creating-token-with-groups-claim/", "/how-to/sharing-cert/", "/how-to/updating_saml_cert/"]

googleAnalytics = "UA-15777010-3"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
